# Generated by Django 3.2.20 on 2024-02-23 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patid', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('address', models.CharField(max_length=50, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('contactno', models.CharField(max_length=10, null=True)),
                ('bloodgroup', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
