# Generated by Django 3.2.20 on 2024-02-23 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ODBS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('docid', models.BigAutoField(primary_key=True, serialize=False)),
                ('contactno', models.CharField(max_length=50, null=True)),
                ('qualification', models.CharField(max_length=50, null=True)),
                ('specialist', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
