# Generated by Django 3.2.20 on 2024-02-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ODBS', '0003_patient_docid'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('appid', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=50, null=True)),
                ('starttime', models.TimeField(max_length=50, null=True)),
                ('docid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ODBS.doctor')),
                ('patid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ODBS.patient')),
            ],
        ),
    ]
