# Generated by Django 3.2.20 on 2024-03-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODBS', '0005_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='day1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='day2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='day3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='time1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='time2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='time3',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
