# Generated by Django 3.2.20 on 2024-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODBS', '0006_auto_20240313_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dept',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
